-- MySQL Script generated by MySQL Workbench
-- Sun Mar  4 22:47:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`SUPLIERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SUPLIERS` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `zip` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COFFEES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COFFEES` (
  `name` VARCHAR(100) NOT NULL,
  `sales` VARCHAR(45) NOT NULL,
  `total` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `SUP_ID` INT NOT NULL,
  PRIMARY KEY (`name`),
  INDEX `fk_COFFEES_SUPLIERS_idx` (`SUP_ID` ASC),
  CONSTRAINT `fk_COFFEES_SUPLIERS`
    FOREIGN KEY (`SUP_ID`)
    REFERENCES `mydb`.`SUPLIERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
